exports.artists =   [{ name:"Linkin Park", vote: "up", speak:"", dislike: false },
					{name: "Skrillex", vote:"down", speak:"Gah! I have heard drunken dwarves sing better!", dislike: true },
					{name: "Coldplay", vote:"down", speak:"Me like banshee song better than this!", dislike: true },
					{name: "Bob Marley", vote:"up", speak:"/me takes a toke and offers it to others.", dislike: true },
					{name: "Matthew Ebel", vote:"up", speak:"LOVE this dude!", dislike: false },
					{name: "Eminem", vote:"up", speak:"", dislike: false },
					{name: "Cake", vote:"up", speak:"Me like cake...", dislike: false },
					{name: "Jonathan Coulton", vote:"up", speak:"", dislike: false },
					{name: "Kid Rock", vote:"up", speak:"", dislike: false },
					{name: "Rebecca Black", vote:"down", speak:"NOOOOOOOOOOO!!!!!!!!!!! My ears!!!! They bleed!!!!", dislike: true },
					{name: "Justin Bieber", vote:"down", speak:"NOOOOOOOOOOO!!!!!!!!!!! My ears!!!! They bleed!!!!", dislike: true },
					{name: "Hannah Montana", vote:"down", speak:"NOOOOOOOOOOO!!!!!!!!!!! My ears!!!! They bleed!!!!", dislike: true },
					{name: "Miley Cyrus", vote:"down", speak:"NOOOOOOOOOOO!!!!!!!!!!! My ears!!!! They bleed!!!!", dislike: true },
					{name: "Will Smith", vote:"up", speak:"", dislike: false },
					{name: "Starship", vote:"up", speak: "Ahh Aliens!!", dislike: false}
					/*{name: "Queen", vote:"up", speak:"Me thinks that @Lord of Nerds plays these guys too much.", dislike: false }*/
					];

exports.songs =     [{ name:"Baby Got Back", vote: "up", speak: "/me sings with the song.", dislike: false},
                    { name:"Skrillex", vote: "down", speak: "Gah! I have heard drunken dwarves sing better!", dislike: true},
					{ name:"Jump Around", vote: "up", speak: "/me jump, jump, jumps", dislike: false},
					{ name:"Code Monkey", vote: "up", speak: "GEEK!!", dislike: false},
					{ name:"Everybody needs a", vote: "up", speak: "You sure do!", dislike: false},
					{ name:"When Worlds Collide", vote: "up", speak: "/me moshes", dislike: false},
					{ name: "Sexy And I Know It", vote: "up", speak: "You know you want me ladies. Dwarves have high constitutions, we can go ALL NIGHT LONG!", dislike: false}
					];
                    
exports.genres =    [{ name:"Dubstep", vote: "down", speak: "This shit not welcome here. DEATH TO ALL DUBSTEP!", dislike: true},
					{ name:"Rock", vote: "up", speak: "", dislike: false},
					{ name:"Country", vote: "up", speak: "", dislike: false}
                    ];

exports.chat_responses =	[{ name: "whois", response1: "Me is a bot that is created by @PodcastMike. Me guts are at https://github.com/MikeWills/Uglee.", response2: "" },
							{ name: "speak", response1: "GWAAAARRRRR!!!!!", response2: "" },
							{ name: "300", response1: "THIS. IS SPARTA!!!!!!", response2: "" },
							{ name: "ping", response1: "pong", response2: ""},
							{ name: "bye", response1: "Finally that jerk is leaving.", response2: "" },
							{ name: "hammer", response1: "The hammer is my penis.", response2: "" },
							{ name: "menu", response1: "Here is my drink menu: whiskey | brandy | tequilla | gin | coke | dew | coffee | water.",
									response2: "Here is my food menu: pizza | cake | taquitos"},
							{ name: "beer", response1: "/me hands @{0} a cold one.", response2: "Here you go Master @{0}." },
							{ name: "whiskey", response1: "/me hands @{0} a Crown Royal on the rocks.", response2: "Here you go Master @{0}." },
							{ name: "brandy", response1: "/me hands @{0} a E&J VSOP on the rocks.", response2: "Here you go Master @{0}." },
							{ name: "tequila", response1: "/me hands @{0} a shot of 1800 Select Silver.", response2: "Here you go Master @{0}. Real men (and women) don't need limes and salt." },
							{ name: "tequilla", response1: "/me hands @{0} a shot of 1800 Select Silver.", response2: "Here you go Master @{0}. Real men (and women) don't need limes and salt." },
							{ name: "taquila", response1: "/me hands @{0} a shot of 1800 Select Silver.", response2: "Here you go Master @{0}. Real men (and women) don't need limes and salt." },
							{ name: "taquilla", response1: "/me hands @{0} a shot of 1800 Select Silver.", response2: "Here you go Master @{0}. Real men (and women) don't need limes and salt." },
							{ name: "gin", response1: "/me hands @{0} a Hendricks with soda and lemon.", response2: "Here you go Master @{0}." },
							{ name: "wine", response1: "What are you some fucking pussy elf?", response2: "" },
							{ name: "coke", response1: "/me hands @{0} a cold one.", response2: "Here you go Master @{0}." },
							{ name: "dew", response1: "/me hands @{0} a Mt. Dew.", response2: "Here you go Master @{0}. Like to do the Dew huh?" },
							{ name: "coffee", response1: "/me hands @{0} a large cup of liquid energy.", response2: "Here you go Master @{0}." },
							{ name: "water", response1: "Do we serve water here??", response2: "HELL NO H2O!!" },
							{ name: "pot", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "joint", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "weed", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "grass", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "blunt", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "cocaine", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "lsd", response1: "Drugs are byad! Mkay?", response2: "" },
							{ name: "Taquitos", response1: "Stop trying to break me @Lord of Nerds!", response2: "" },
							{ name: "cake", response1: "Mmmm cake!", response2: "/me cuts a slice and hands it to @{0}." },
							{ name: "pizza", response1: "Mmmm pizza!", response2: "/me cuts a slice and hands it to @{0}." },
							{ name: "fart", response1: "/me lets a really smelly one fly.", response2: "" },
							{ name: "dance bitch", response1: "... fine.", response2: "/me dances." },
							{ name: "dance", response1: "Dwarves don't dance Master @{0}", response2: "" },
							{ name: "mosh", response1: "/me starts the mosh pit.", response2: "" },
							{ name: "whore", response1: "You want some of THIS baby?? Me can go ALL NIGHT LONG!!", response2: "" },
							{ name: "zombies", response1: "Zombies? KILL THE ZOMBIES!!!", response2: "/me pulls out axe and starts to kill all the zombies." },
							{ name: "lamer", response1: "Lamers? Let me at them master! I'll KILL THE LAMER!!!", response2: "/me pulls out axe and starts to hunt for the lamer." },
							{ name: "nazis", response1: "Nazis? KILL THE NAZIS!!!", response2: "/me pulls out axe and starts to kill all the Nazis." },
							{ name: "ninja", response1: "Go ninja, Go ninja!", response2: "Go ninja go!" },
							{ name: "thank you", response1: "Your welcome!", response2: ""},
							{ name: "thanks", response1: "Your welcome!", response2: ""},
							{ name: "love", response1: "I love you too @{0}", response2: ""},
							{ name: "= awesome!", response1: "@{0} = Looser!", response2: ""},
							{ name: "= gay", response1: "@{0} suck it!", response2: ""},
							{ name: "your mom", response1: "My momma? Let's talk about how your momma squeeled like a pig last night as I was giving her the dwarven hammer...", response2: "The hammer's my penis."},
							{ name: "friday", response1: "If you play that fucking Rebecca Black song, I'll pluck your pubes out one at a time and force feed them to you.", response2: ""},
							{ name: "dubstep", response1: "Dubstep isn't music and that shit not welcome here. DEATH TO ALL DUBSTEP! ", response2:"This is what dubstep is: http://youtu.be/z_SQO3vv3p8"},
							{ name: "queue", response1: "There is no queue. Just be the fastest person to step up!", response2: "" },
							{ name: "roll", response1: "Hey DJs. If you like to gamble and it's your turn; type 'roll'. I'll roll a dice for you. A 5 and 6 means I give you an awesome. 2-4 is nothing. If I roll a 1, however, I give you a lame. So be sure you want to roll.", response2: "" },
							{ name: "suck it", response1: "8==:fist:==D:sweat_drops: :lips:", response2: "" }
							];
